variables:
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  HUB_IMAGE: monachus/wordpress
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

stages:
  - prep
  - build
  - release

build_wordpress:
  stage: prep
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  variables:
    GIT_SUBMODULE_STRATEGY: none
  artifacts:
    name: "$CI_JOB_NAME"
    paths: 
     - site/wordpress
    expire_in: 1 hour
  script:
    - umask 022
    - apk --no-cache add git
    - ls -al
    - cd site/wordpress
    - git submodule init
    - git submodule update
  except:
    - master

build_image:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  dependencies:
    - build_wordpress
  script:
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE
  except:
    - master

push_to_docker_hub:
  stage: release
  script:
    - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
    - docker tag $IMAGE $HUB_IMAGE:$CI_BUILD_REF_NAME
    - docker tag $IMAGE $HUB_IMAGE:latest
    - docker push $HUB_IMAGE:$CI_BUILD_REF_NAME
    - docker push $HUB_IMAGE:latest
  only:
    - tags
