variables:
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  LATEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest
  DEV_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:develop
  HUB_IMAGE: monachus/wordpress
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

services:
  - docker:dind

stages:
  - prep
  - build
  - release_tags
  - release_master

build_submodules:
  stage: prep
  image: docker:stable
  variables:
    GIT_SUBMODULE_STRATEGY: none
  artifacts:
    name: "$CI_JOB_NAME"
    paths: 
     - site/wordpress
     - pswp
    expire_in: 1 hour
  script:
    - umask 022
    - apk --no-cache add git
    - ls -al
    - git submodule init
    - git submodule update

build_standard_image:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  dependencies:
    - build_wordpress
  script:
    - docker pull $LATEST_IMAGE || true
    - docker build --cache-from $LATEST_IMAGE -t $IMAGE .
    - docker push $IMAGE
    - docker pull $LATEST_IMAGE-pv || true
    - docker build --cache-from $LATEST_IMAGE-pv -t $IMAGE-pv -f Dockerfile.pv .
    - docker push $IMAGE-pv
  except:
    - master

push_tags:
  image: docker:stable
  stage: release_tags
  script:
    - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
    - docker pull $IMAGE
    - docker pull $IMAGE-pv
    - docker tag $IMAGE $HUB_IMAGE:$CI_BUILD_REF_NAME
    - docker tag $IMAGE-pv $HUB_IMAGE:$CI_BUILD_REF_NAME-pv
    - docker push $HUB_IMAGE:$CI_BUILD_REF_NAME
    - docker push $HUB_IMAGE:$CI_BUILD_REF_NAME-pv
  only:
    - tags

push_master:
  image: docker:stable
  stage: release_master
  script:
    - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
    - docker pull $IMAGE
    - docker pull $IMAGE-pv
    - docker tag $IMAGE $HUB_IMAGE:latest
    - docker tag $IMAGE-pv $HUB_IMAGE:latest-pv
    - docker push $HUB_IMAGE:latest
    - docker push $HUB_IMAGE:latest-pv
  only:
    - master
