variables:
  IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  DOCKER_IMAGE: monachus/$CI_PROJECT_PATH_SLUG

stages:
  - prep
  - build
  - release

build_wordpress:
  stage: prep
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    WORDPRESS_VERSION: 4.8.1
  artifacts:
    name: "$CI_JOB_NAME"
    untracked: true
    paths: 
     - site/wordpress
    expire_in: 1 hour
  script:
    - apk --no-cache add git
    - cd site/wordpress
    - git checkout $WORDPRESS_VERSION

build_image:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  dependencies:
    - build_wordpress
  script:
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE

push_to_docker_hub:
  stage: release
  script:
    - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
    - docker tag $IMAGE $DOCKER_IMAGE:$CI_BUILD_REF_NAME
    - docker tag $IMAGE $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_BUILD_REF_NAME
    - docker push $DOCKER_IMAGE:latest
  only:
    - tags
